version: "3"
services:
  testapp:
    image: io.c19.test/flask-app-01
    sysctls:
      net.core.somaxconn: 1024
    deploy:
      replicas: 2
    ports:
      - "5000:5000"
    networks:
      - webnet

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "7080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  webnet: